name: bd
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  connect_to_sql_server_directly: ^0.0.1
  mysql1: ^0.20.0

  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
